[package]
name = "cratery"
version = "1.0.0"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
description = "Cratery -- a private cargo registry"
repository = "https://github.com/cenotelie/cratery"
homepage = "https://github.com/cenotelie/cratery"
documentation = "https://github.com/cenotelie/cratery"
license = "LGPL-3.0"
edition = "2021"
publish = ["cenotelie"]

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
byteorder = "1.4"
mime = "0.3"
rand = "0.8"
data-encoding = "2.1"
urlencoding = "2.1"
ring = "0.17"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = {version = "0.7", features = ["io"]}
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "macros", "chrono"] }
axum = { version = "0.7", features = [] }
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls"] }
cenotelie_lib_log = { version = "1.1", registry = "cenotelie" }
cenotelie_lib_apierror = { version = "2", registry = "cenotelie" }
cenotelie_lib_licenses = { version = "1.3", registry = "cenotelie" }
cenotelie_lib_async_utils = { version = "1.13", registry = "cenotelie" }
cenotelie_lib_dbutils = { version = "3.4", registry = "cenotelie" }
cenotelie_lib_axum_utils = { version = "3.3", registry = "cenotelie" }
cenotelie_lib_axum_static_files = { version = "1", registry = "cenotelie" }
cenotelie_lib_s3 = { version = "3", registry = "cenotelie" }
