[package]
name = "cratery"
version = "1.3.1"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
description = "Cratery -- a private cargo registry"
repository = "https://github.com/cenotelie/cratery"
homepage = "https://github.com/cenotelie/cratery"
documentation = "https://github.com/cenotelie/cratery"
license = "MIT"
edition = "2021"
publish = ["cenotelie"]

[dependencies]
log = "0.4"
fern = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
byteorder = "1.4"
base64 = "0.22"
cookie = { version = "0.18", features = ["secure", "percent-encode"] }
mime = "0.3"
rand = "0.8"
data-encoding = "2.1"
urlencoding = "2.1"
ring = "0.17"
flate2 ="1.0"
tar = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = {version = "0.7", features = ["io"]}
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "macros", "chrono"] }
axum = { version = "0.7", features = [] }
reqwest = { version = "0.12", default-features = false, features = ["stream", "rustls-tls"] }
cenotelie_lib_s3 = { version = "3.2", registry = "cenotelie" }
